version: '2'
services:
  artemisdorm-app:
    image: artemisdorm
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://artemisdorm-mysql:3306/artemisdorm?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  artemisdorm-mysql:
    extends:
      file: mysql.yml
      service: artemisdorm-mysql
